[package]
name = "gi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
log = "0.4.20"
serde = { version = "1.0.195", features = ["derive"] }
slug = "0.1.5"
toml = "0.8.8"
